### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by DmytroLitvinov** [PragmaticMates/django-whistle#2]
Wow. That package has 2.3.0 version and was released 4 years ago but there is no documentation in README.md about what is it :)

**Comment by eriktelepovsky** [comment]
Hi. Yeah, sorry. I created it mainly for personal purposes but it become useful package actually. It delivers functionality for web and native mobile notifications of custom events with cache optimisation. I will definitely need to update the README file already :)
